modLoader="javafml"
loaderVersion="[40,)"
license="Academic Free License v3.0"

[[mods]]
modId="trident_crafting__structures_two"
version="1.0.0"
displayName="Trident_crafting_&_structures_two"
credits="Created using mod maker MCreator - https://mcreator.net/about"
displayURL="https://mcreator.net"
authors="Hiros, MCreator"

[[dependencies.trident_crafting__structures_two]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.18.2]"
    ordering="NONE"
    side="BOTH"




